import "/src/styles/style.scss";
import "/src/component/header/header.js";
import "/src/component/footer/footer.js";
import "/src/component/recent-product/main.js";
// import "/src/component/product/product-slide.js";
// import "/src/component/product/product-slide2.js";
import "/src/component/product/test.js";
import "/src/component/banner/banner.js";
import "/src/component/pop-up/main.js";
import "/src/component/topBanner/topBanner.js";
